name: projet_prog_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - images/navbar_home.png
    - images/navbar_comics.png
    - images/navbar_movies.png
    - images/navbar_search.png
    - images/navbar_series.png
    - images/astronaut.png
    - images/ic_books_bicolor.png
    - images/ic_calendar_bicolor.png
    - images/ic_movie_bicolor.png
    - images/ic_publisher_bicolor.png
    - images/ic_tv_bicolor.png

  uses-material-design: true